# Generated by Django 5.2.17 on 2026-09-19 18:07

import django.contrib.postgres.constraints
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('identification', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'propietario',
                'verbose_name_plural': 'propietarios',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('professional_id', models.CharField(max_length=50, unique=True)),
                ('specialty', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'profesional',
                'verbose_name_plural': 'profesionales',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'tipo de consulta',
                'verbose_name_plural': 'tipos de consulta',
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('duration_minutes__gt', 0)), name='consultation_duration_is_positive')],
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=80)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('sex', models.CharField(blank=True, max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('vital_status', models.CharField(choices=[('ALIVE', 'Viva'), ('DECEASED', 'Fallecida')], default='ALIVE', max_length=10)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pets', to='veterinary.owner')),
            ],
            options={
                'verbose_name': 'mascota',
                'verbose_name_plural': 'mascotas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(editable=False)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Programada'), ('ATTENDED', 'Atendida'), ('CANCELED', 'Cancelada'), ('NO_SHOW', 'Inasistencia')], default='SCHEDULED', max_length=10)),
                ('cancellation_requested_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='veterinary.consultationtype')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='veterinary.pet')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='veterinary.professional')),
            ],
            options={
                'verbose_name': 'cita',
                'verbose_name_plural': 'citas',
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.TextField()),
                ('diagnosis', models.TextField(blank=True)),
                ('treatment', models.TextField(blank=True)),
                ('medications', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visit', to='veterinary.appointment')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='veterinary.pet')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='veterinary.professional')),
            ],
            options={
                'verbose_name': 'atención registrada',
                'verbose_name_plural': 'atenciones registradas',
                'ordering': ['-attended_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='pet',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('death_date__isnull', True), ('vital_status', 'ALIVE')), models.Q(('death_date__isnull', False), ('vital_status', 'DECEASED')), _connector='OR'), name='pet_status_matches_death_date'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['professional', 'starts_at'], name='veterinary__profess_5ef45c_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['pet', 'starts_at'], name='veterinary__pet_id_abb83b_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status', 'SCHEDULED')), expressions=[(models.Func('starts_at', 'ends_at', models.Value('[)'), function='TSTZRANGE'), '&&')], name='scheduled_appointments_do_not_overlap'),
        ),
    ]
