# Generated by Django 5.2.17 on 2026-09-19 18:40

import django.contrib.postgres.constraints
import django.contrib.postgres.operations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0001_initial'),
    ]

    operations = [
        django.contrib.postgres.operations.BtreeGistExtension(),
        migrations.RemoveConstraint(
            model_name='appointment',
            name='scheduled_appointments_do_not_overlap',
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status', 'SCHEDULED')), expressions=[('professional', '='), (models.Func('starts_at', 'ends_at', models.Value('[)'), function='TSTZRANGE'), '&&')], name='scheduled_appointments_do_not_overlap'),
        ),
    ]
